// <auto-generated />
using System;
using GBC_Travel_Group_32.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GBC_Travel_Group_32.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240214162601_Listing")]
    partial class Listing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GBC_Travel_Group_32.Models.Listing", b =>
                {
                    b.Property<int>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingId"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ListingId");

                    b.ToTable("Listings");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Listing");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GBC_Travel_Group_32.Models.CarRental", b =>
                {
                    b.HasBaseType("GBC_Travel_Group_32.Models.Listing");

                    b.HasDiscriminator().HasValue("CarRental");
                });

            modelBuilder.Entity("GBC_Travel_Group_32.Models.Flight", b =>
                {
                    b.HasBaseType("GBC_Travel_Group_32.Models.Listing");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxPassengers")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Flight");
                });

            modelBuilder.Entity("GBC_Travel_Group_32.Models.Hotel", b =>
                {
                    b.HasBaseType("GBC_Travel_Group_32.Models.Listing");

                    b.Property<DateTime>("EndPeriod")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rooms")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartPeriod")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Hotel");
                });
#pragma warning restore 612, 618
        }
    }
}
